### ISSUE TITLE
Bluetooth incompatibility

### ISSUE THREAD

**Issue by ghost** [KitronikLtd/pxt-kitronik-smart-greenhouse#2]
Hi, I want to send sensor data to phone over UART, but this extension isn't compatible with the bluetooth one. I really need them both in one program so please help.
Thanks in advance.

**Comment by AlasdairAtKitronik** [comment]
@aleksazskola Yes, this extension is intentionally not compatible with bluetooth due to the addressable ZIP LEDs. The bluetooth and ZIP LED operations are timing critical and as there are some limitations with the micro:bit it is not possible to run these processes together.

For your project, as long as you're willing to not use the ZIP LEDs, I have created a version of the extension which is bluetooth compatible: https://github.com/AlasdairAtKitronik/pxt-kitronik-smart-greenhouse.

Copy and paste the link above into the search which opens when you add an extension and you'll find the modified version. You will then be able to include the bluetooth extension as well.

I hope this helps!

**Comment by ghost** [comment]
Thanks a lot! It really helps!
